### ISSUE TITLE
Update testng and guava for security patches

### ISSUE THREAD

**Issue by smugleafdev** [AutomatedOwl/allure-enivonment-writer#10]
Dependabot has [two open PRs](https://github.com/AutomatedOwl/allure-environment-writer/pulls?q=is%3Aopen+is%3Apr). They are tied to active CVEs. It would be helpful if they were accepted and a new release pushed.

**Comment by AutomatedOwl** [comment]
done

**Comment by sphanley** [comment]
Thanks for the action on this, @AutomatedOwl! I'm sad to report though that unfortunately Dependabot has led things astray here – because of the odd ordering of the releases, it apparently superseded its PR for 7.7.0 with 7.5.1, rather than 7.7.1 or 7.8.0. [CVE-2022-4065](https://nvd.nist.gov/vuln/detail/CVE-2022-4065) is fixed in versions > 7.7.0, so is there any chance you'd be able to update further to 7.7.1 or 7.8.0?
